
GRID_SIZE = 200
NUM_CIVS = 10
SEED = None  # Set to None to randomize

SCALE = 75.0
OCTAVES = 6
PERSISTENCE = 0.5
LACUNARITY = 2.0
LAND_THRESHOLD = 0.4

BASE_EXPANSION_CHANCE = 0.25
EXPANSION_SCALE_FACTOR = 50
GROUP_PUSH_LIMIT = 10
SPEED_MULTIPLIER = 2
WAR_COOLDOWN = 50
PEACE_TREATY_COOLDOWN = 200
PEACE_CHANCE = 0.01
WAR_INTENSITY_GROWTH = 0.01
MAX_WARS = 4
ANNEXATION_THRESHOLD = 0.5
